modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]

modId="create_tacz"

version="1.20.1-1.0.0"

displayName="Create Tacz"

authors="FRNc"

description='''以机械动力的方式生产 TaCZ 枪械与弹药。'''

[[dependencies.create_tacz]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.create_tacz]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.create_tacz]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.create_tacz]]
modId="tacz"
mandatory=true
versionRange="${tacz_version_range}"
ordering="NONE"
side="BOTH"
